# Generated by Django 4.2.2 on 2023-06-25 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='categoria',
        ),
    ]
